### ISSUE TITLE
Refactor build tasks

### ISSUE THREAD

**Issue by Cobster** [Cobster/psst#4]
- Consider splitting each task into a separate script file.  
- This would be easier to manage and create new tasks.
- Create a function to generate new build tasks

**Comment by Cobster** [comment]
FooBar

**Comment by MarkPflug** [comment]
blah

**Comment by MarkPflug** [comment]
test2

**Comment by MarkPflug** [comment]
test3

**Comment by Cobster** [comment]
![huron_logo_a_300dpi](https://cloud.githubusercontent.com/assets/573704/26704465/26e6d554-46e4-11e7-9773-679b15bd65b4.jpg)

**Comment by Cobster** [comment]
[hello.txt](https://github.com/Cobster/psst/files/1046257/hello.txt)
